package com.android.oobe.application.model;

public enum EventType {

    DOWNLOAD_PENDING,
    DOWNLOAD_START,
    DOWNLOAD_IN_PROGRESS,
    DOWNLOAD_COMPLETED,
    DOWNLOAD_STOP,

    INSTALL_STARTED,
    INSTALL_IN_PROGRESS,
    INSTALL_COMPLETED,

    DOWNLOAD_FAILED,
    INSTALL_FAILED
}
